power: 8916: Remove unused parameter
hardware/qcom/power/power-8916.c:80:50: error: unused parameter 'data' [-Werror,-Wunused-parameter]

test: Compiles.
Change-Id: I1e580d2574860fcfce4fcaa5cdd42f29456e4931